import type { Metadata } from 'next'
import './globals.css'
import { Taskbar } from './components/taskbar'
import { ReduxProvider } from './providers/redux-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-primary h-screen overflow-hidden bg-cover bg-no-repeat">
        <ReduxProvider>
          {children}
          <Taskbar />
        </ReduxProvider>
      </body>
    </html>
  )
}
